INSERT INTO store.items (name, description, quantity, price) VALUES (
('Flex Tape', 'Its the best on the market!', 25, 10.99),
('Pear', 'The freshest of pears straight from farmers', 35, 1),
('Apple', 'The freshest of apples just for you', 40, 1),
('pack of water', 'Bottled water from the peaks of mountains', 50, 10),
('steak', 'the juiciest of steaks yet', 50, 2.99),
('Lettuce', 'the greenest of lettuce', 30, 4.99),
('Broccoli', 'The best broccoli you will ever have', 70, 0.75),
('Onion', 'delicious onions', 45, 0.5),
('Milk', 'tasty milk', 45, 2.99),
('chocolate bar', 'a tasty snack', 20, 1.99),
('ice cream', 'delicious ice cream', 20, 2.99),
('apple juice', 'yummy apple juice', 20, 3.99),
('grapes', 'fresh and juicy grapes', 40, 1.99),
('strawberries', 'fresh and tasty strawberries', 40, 2.99),
('orange juice', 'tasty orange juice', 20, 6.99),
('Chicken', 'delicious chicken', 40, 2.49),
('Cookies', 'tasty cookies', 40, 1.29),
('Soda', 'refreshing soda', 40, 2.99),
('Coffee', 'coffee for your day', 40, 1.99));