import util.Message;

public enum  ServerTopic implements Message.Topic {
    SERVER_RECEIVE_CLIENT_ACTION,

    SERVER_RECEIVE_CLIENT_REQUEST_REGISTRATION,
    SERVER_RESPONSE_CLIENT_REQUEST_REGISTRATION,

    SERVER_RECEIVE_CLIENT_REQUEST_TOKEN,
    SERVER_RESPONSE_CLIENT_REQUEST_TOKEN,

    SERVER_RECEIVE_CLIENT_REQUEST_ITEM_DATA,
    SERVER_RESPONSE_CLIENT_REQUEST_ITEM_DATA,

    SERVER_RECEIVE_REQUEST_SYNC_CART_DATA,
    SERVER_RESPONSE_CLIENT_REQUEST_SYNC_CART_DATA,

    SERVER_RECEIVE_CLIENT_REQUEST_CHECKOUT,
    SERVER_RESPONSE_CLIENT_REQUEST_CHECKOUT,

    SERVER_RECEIVE_DATABASE_RESPONSE,
    SERVER_REQUEST_DATABASE_ACTION;
}
