import util.Message;

public enum ClientTopic implements Message.Topic {
    CLIENT_RECEIVE_SERVER_RESPONSE,
    CLIENT_REQUEST_SERVER_ACTION,

    CLIENT_REQUEST_REGISTRATION,
    CLIENT_RECEIVE_REGISTRATION,

    CLIENT_REQUEST_TOKEN,
    CLIENT_RECEIVE_TOKEN,

    CLIENT_REQUEST_ITEM_DATA,
    CLIENT_RECEIVE_ITEM_DATA,

    CLIENT_REQUEST_SYNC_CART_DATA,
    CLIENT_RECEIVE_SYNC_CART_DATA,

    CLIENT_REQUEST_CART_DATA,
    CLIENT_RECEIVE_CART_DATA,

    CLIENT_REQUEST_CHECKOUT,
    CLIENT_RECEIVE_CHECKOUT
}
